% "extended" gene lists found on basis of co-expression, physical interaction by Chenyan
% 	pulled from Chenyang's spreadsheet GENEMANIA_CANCER_MOUSE_PATHWAY_ANALYSIS_V5 > NEW_GENELIST tab
% group order here should be same as in getOrigGenelists(), this is an assumption we're relying on later down the line
function genes_new = getExtendedGenelists()
	genes_new = { ...
		{ 'REACTOME_SOS_MEDIATED_SIGNALLING', 'Rassf5', 'Shoc2', 'Gab1', 'Igf1r', 'Kcnk3', 'Il4ra', 'Ptprr', 'Tlk2', 'Pik3r3' }, ...
		{ 'BIOCARTA_CERAMIDE_PATHWAY', 'Dusp6', 'Cebpb', 'Atg5', 'Pea15a', 'Ywhaq' }, ...
		{ 'REACTOME_NOTCH_HLH_TRANSCRIPTION_PATHWAY', 'Notch1', 'Dll1', 'Egfl7', 'Taf5l', 'Gli3', 'Ncor2', 'Jag2', 'Cntn1', 'Dll4', 'Aph1a', 'Phf2', 'Tada2a' }, ...
		{ 'MOOTHA_FFA_OXYDATION', 'Etfa', 'Ech1', '5033411D12Rik', 'Hsdl2', 'Plin5', 'Slc25a20', 'Etfb', 'Eci2', 'Ivd', 'Ptgr2', 'Hibadh', 'Hibch', 'Acad12', 'Etfdh', 'Clybl', 'Dbt', 'D2hgdh', 'Lmf1' }, ...
		{ 'REACTOME_PROCESSIVE_SYNTHESIS_ON_THE_LAGGING_STRAND', 'Tipin', 'Timeless', 'Blm', 'Fam96b', 'Rmi1' }, ...
		{ 'LANDIS_BREAST_CANCER_PROGRESSION_UP', 'Epcam', 'Esrp1', 'Ceacam1', 'Rhpn2', 'Wfdc18', '1600029D21Rik', 'Sh3bgrl2', 'Tm9sf3', 'Cdcp1', 'Erbb3', 'Crb3', 'Tmem30b', 'Serinc3', 'Arhgef5', 'Knop1', 'Krt18', 'Krt8', 'Arfgap3' }, ...
		{ 'GOTZMANN_EPITHELIAL_TO_MESENCHYMAL_TRANSITION_UP', 'Sparc', 'Postn', 'Col1a2', 'Lox', 'Nid1', 'Smc2', 'Fbn1', 'Ect2', 'Hspg2', 'Eln', 'Mcm4', 'C330027C09Rik', 'Lum', 'Ccna2', 'Myadm', 'Thbs2', 'Mad2l1' }, ...
		{ 'INGA_TP53_TARGETS', 'Errfi1', 'Dctn2', 'Ccnd2', 'Dhcr24', 'Tbl3', 'Casp3', 'Bnc1', 'Schip1', 'Moap1', 'Rpl11', 'Mtbp', 'Atf7' }, ...
		{ 'NIKOLSKY_BREAST_CANCER_21Q22_AMPLICON', 'Col6a3', 'Eny2', 'Gem', 'Rabgap1', 'Rnps1', 'Clstn1', 'Akap9', 'Rbm10', 'Tgm2', 'Tnik' }, ...
		{ 'REACTOME_POL_SWITCHING', 'Prpf38a', 'Poldip3', 'Wdhd1', 'Rel', 'Chaf1a', 'Chtf18', 'Cnot8', 'Rqcd1', 'Mrpl38', 'Cnot6', 'Enoph1', 'Lsm6', 'Metap2', 'Uso1', 'Stk40', 'Kctd13' }, ...
		{ 'CROMER_METASTASIS_DN', 'Flot2', 'Krt6a', 'Krt14', 'Tacstd2', 'Krt17', 'Dynll1', 'Dsp', 'Perp', 'Pkp3', 'Lama3', 'Ckm', 'Itga6', 'Dtx3', 'Dsc1', 'Dnm1', 'Eml1', 'Cand2' }, ...
		{ 'SA_PROGRAMMED_CELL_DEATH', 'Bok', 'Bik', 'Sp100', 'Card11', 'Dnm1l', 'Bcl2l14', 'Bmf', 'Bcl2l10', 'Hrk' }, ...
		{ 'BOGNI_TREATMENT_RELATED_MYELOID_LEUKEMIA_DN', 'Rala', 'Cdk4', 'Hipk2', 'Nlk', 'Ppp2r5a', 'Nrip1', 'Poldip2', 'Rara', 'Ptprm', 'Ppp2r5c', 'Wdr77', 'Synpo', 'Exoc1', 'Creb3l4' }, ...
		{ 'KEGG_SNARE_INTERACTIONS_IN_VESICULAR_TRANSPORT', 'Stx4a', 'Azi1', 'Aimp1', 'Clip2', 'Stx5a', 'Napa', 'Lztfl1', 'Uaca', 'Gcc1', 'Ift57', 'Tmcc2', 'Vps16', 'Vps53', 'Exoc5', 'Abi2', 'Stxbp6' }, ...
		{ 'FLECHNER_BIOPSY_KIDNEY_TRANSPLANT_OK_VS_DONOR_DN', 'Dcc', 'Ddx52', 'Cxxc1', 'Rps9', 'Grlf1', 'Dnajc1', 'A2m', 'Snx9', 'Plscr1', 'Snx33', 'Slc17a9', 'Apbb2' }, ...
		{ 'MOSERLE_IFNA_RESPONSE', 'Oasl2', 'Irf7', 'Parp9', 'Parp14', 'Dhx58', 'Stat2', 'Mx2', 'Slfn8', 'Trim25', 'Zbp1', 'Gbp6', 'Xaf1', 'Isg15' }, ...
		{ 'HUANG_DASATINIB_RESISTANCE_UP', 'Tgfbr1', 'Gbp2', 'Igtp', 'Irgm2', 'Irgm1', 'Gbp7', 'Ifi47', 'Tgfb1', 'Ilk', 'Tap1', 'Ly6a', 'Cyb5r3', 'Tpm4', 'Il15' }, ...
		{ 'KEGG_BASE_EXCISION_REPAIR', 'Aplf', 'Snrpf', 'Msh6', 'Lrsam1', 'Chrac1', 'Exo1', 'Stk19', 'Dr1', 'Aptx', 'Polm', 'Gen1', 'Dntt', 'Lig4', 'Rev3l', 'Tle1', 'Ercc5' }, ...
		{ 'PID_CERAMIDE_PATHWAY', 'Mcl1', 'Cflar', 'Trpc4ap', 'Traf1', 'Fas', 'Ikbkg', 'Stat3', 'Tnfrsf1b', 'Lamtor2', 'Brap', 'Bcl2l2', 'Braf', 'Casp2', 'Mapk8ip3', 'Lrdd', 'Bcl2a1a' }, ...
		{ 'MILI_PSEUDOPODIA_CHEMOTAXIS_DN', 'SERPINH1', 'COL4A2', 'MANF', 'CRTAP', 'PRKCSH', 'LEPREL2', 'LAMB1', 'HSP90B1', 'CYR61', 'SEC31A', 'CTSA', 'NID1', 'TPM4', 'NUCB1', 'HEXA', 'ANXA5', '0610031J06RIK', 'PLOD3', 'TPP1', 'COL6A2' } ...
	};
end